# Generated by Django 5.0 on 2023-12-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_category_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
